"""
llm.py — The Language Model Interface

This module owns all interactions with Ollama/Llama 3. Two responsibilities:
  1. Build a well-engineered prompt from retrieved chunks + user question
  2. Call Ollama and return the generated answer

WHY A SEPARATE MODULE?
The prompt design and LLM call are the most sensitive parts of the system.
If answer quality degrades, this is where you tune it. Keeping it isolated
means you can swap the prompt template, change the model, or switch from
Ollama to another provider without touching any route or retrieval code.

FUNCTIONS EXPORTED:
  generate_answer(chunks, question) → str
      Full blocking generation. Returns the complete answer as a string.
      Used by Phase 4's /chat/query endpoint.

  stream_answer(chunks, question) → Generator[str, None, None]
      Yields tokens as they're generated by the LLM.
      Used by Phase 5's /chat/stream endpoint for the React frontend.
"""

from typing import Generator, List

import ollama
from langchain_core.documents import Document

from app.config import settings


# ================================================================== #
#  Prompt Design                                                       #
# ================================================================== #

# THE SYSTEM PROMPT — The rules Llama 3 must follow for every response.
#
# Design principles:
#   1. Define the model's identity ("You are CognitiveVault...")
#   2. Establish the information boundary ("ONLY the context below")
#   3. Provide an explicit fallback for unanswerable questions
#      (prevents hallucination when context doesn't cover the query)
#   4. Style guidance (concise, professional, cite page numbers)
#
# This prompt is sent as the "system" role — Llama 3 treats it as
# its core operating instructions rather than as user input.
SYSTEM_PROMPT = """You are CognitiveVault, an expert AI assistant that answers \
questions strictly and exclusively from the document excerpts provided below.

You must follow these rules without exception:
1. Base your answer ONLY on the information in the provided context sections.
2. Do NOT use any external knowledge, assumptions, or information not present \
in the context.
3. If the provided context does not contain enough information to answer the \
question, respond with exactly: "I could not find a clear answer to this \
question in the provided documents."
4. Always be concise, accurate, and professional.
5. When your answer draws from a specific context section, reference the \
page number (e.g. "According to page 7...").
6. Never fabricate names, numbers, dates, or technical details."""


def _build_user_message(chunks: List[Document], question: str) -> str:
    """
    Assemble the context chunks and question into a single user message.

    FORMAT:
        Using the following document excerpts as your only source:

        [Context 1 | CaseStudy.pdf | Page 7 | Relevance: 87.34%]
        "...SQL injection vulnerability was found on the login endpoint..."

        ---

        [Context 2 | CaseStudy.pdf | Page 12 | Relevance: 82.10%]
        "...data was transmitted without TLS encryption..."

        ---

        Question: What were the main security vulnerabilities found?

        Answer:

    WHY WE LABEL EACH CONTEXT WITH PAGE + RELEVANCE:
      - Page number: Lets Llama 3 cite sources in its answer ("on page 7...")
      - Relevance score: Helps the model weight higher-confidence chunks more
    """
    context_blocks = []
    for i, chunk in enumerate(chunks, start=1):
        # metadata keys set in ingestion.py (page is 0-indexed from pypdf)
        page_num = chunk.metadata.get("page", 0)
        filename = chunk.metadata.get("source_filename", "document")
        score = chunk.metadata.get("score", 0.0)

        # page_num is 0-indexed. Add 1 for human-readable display.
        header = (
            f"[Context {i} | {filename} | Page {page_num + 1} "
            f"| Relevance: {score:.2%}]"
        )
        context_blocks.append(f"{header}\n{chunk.page_content.strip()}")

    # Join all context blocks with a visual separator
    context_text = "\n\n---\n\n".join(context_blocks)

    return (
        f"Using the following document excerpts as your ONLY source of information:\n\n"
        f"{context_text}\n\n"
        f"---\n\n"
        f"Question: {question}\n\n"
        f"Answer:"
    )


# ================================================================== #
#  Generation                                                          #
# ================================================================== #

def generate_answer(chunks: List[Document], question: str) -> str:
    """
    Generate a complete answer from retrieved chunks and a question.

    This function is SYNCHRONOUS (no async/await). It blocks until
    Llama 3 finishes generating the full response. For a typical
    question this takes 5–30 seconds on CPU-only hardware.

    FastAPI automatically runs synchronous endpoint functions in a
    thread pool, so this blocking call does NOT freeze the server.

    Args:
        chunks:   Retrieved Document objects from Qdrant (with metadata).
        question: The user's original question string.

    Returns:
        The complete generated answer as a plain string.

    Raises:
        ConnectionRefusedError: if Ollama is not running.
        Exception:              if the model name is wrong or Ollama errors.
    """
    user_message = _build_user_message(chunks, question)

    response = ollama.chat(
        # The model name must match what you pulled with `ollama pull`.
        # Change to "mistral" in .env if you use Mistral instead.
        model=settings.ollama_model,

        # Ollama uses a chat format: a list of {"role": ..., "content": ...}
        # dicts. "system" sets the model's operating instructions.
        # "user" is the actual request containing context + question.
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],

        options={
            # temperature — the creativity/randomness dial.
            # 0.1 = very focused and deterministic.
            # Perfect for document Q&A where we want facts, not creativity.
            "temperature": 0.1,

            # num_ctx — the context window in tokens.
            # 8192 is Llama 3's full context window.
            # This must fit: system prompt + context chunks + question + answer.
            # Our 5 chunks (~5000 chars) + prompts (~500 chars) ≈ 4000 tokens.
            # Well within the 8192 limit.
            "num_ctx": 8192,
        },
    )

    # response.message.content is the generated text.
    # ollama SDK ≥0.3 returns a typed object; use attribute access.
    return response.message.content


def stream_answer(
    chunks: List[Document],
    question: str,
) -> Generator[str, None, None]:
    """
    Stream the answer token-by-token from Ollama.

    Instead of waiting for the full response, this generator yields
    each token as Llama 3 produces it. This enables the React frontend
    to display a live "typing" effect in Phase 5.

    Usage (in a FastAPI StreamingResponse):
        return StreamingResponse(
            stream_answer(chunks, question),
            media_type="text/event-stream"
        )

    Args:
        chunks:   Retrieved Document objects from Qdrant.
        question: The user's question.

    Yields:
        Individual text tokens (strings) as the LLM generates them.
        Each token is typically 1–4 characters (a word fragment or word).
    """
    user_message = _build_user_message(chunks, question)

    # stream=True tells Ollama to yield each token as it's generated
    # instead of waiting for the complete response.
    stream = ollama.chat(
        model=settings.ollama_model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
        stream=True,
        options={"temperature": 0.1, "num_ctx": 8192},
    )

    for chunk in stream:
        # Each chunk.message.content is a token (word fragment).
        # We skip empty tokens (Ollama sometimes yields "" at the end).
        token = chunk.message.content
        if token:
            yield token

    # ── Sources payload ───────────────────────────────────────────────
    # After all text tokens, emit a final special chunk that the React
    # frontend uses to display source citations.
    #
    # PROTOCOL:
    #   \x1e = ASCII Record Separator (character code 30)
    #   This character NEVER appears in LLM-generated text, making it
    #   a safe delimiter. The React client splits on this byte.
    #
    # FORMAT:
    #   "\x1e" + JSON.stringify([{ page, source_filename, score, preview }])
    import json
    sources_payload = [
        {
            # page is 0-indexed in pypdf metadata; +1 for human-readable display
            "page": c.metadata.get("page", 0) + 1,
            "source_filename": c.metadata.get("source_filename", "unknown"),
            "score": round(float(c.metadata.get("score", 0.0)), 4),
            # 120-char preview shown in the sources accordion in the UI
            "preview": c.page_content[:120].strip().replace("\n", " "),
        }
        for c in chunks
    ]
    yield "\x1e" + json.dumps(sources_payload)
